# If deploy on github pages, change baseURL to repo's url
# eg: "https://USERNAME.github.io/" if this is your first website
# or "https://USERNAME.github.io/REPO_NAME/" if not the first
# replace USERNAME and REPO_NAME
# To run locally with 'hugo server' or deploy on Netlify, enable the following line and disable the one after it.
# baseURL = "/"
baseURL = "https://girke.bioinformatics.ucr.edu/GEN242/"
title = "GEN242"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit", "\\.utf8"]
enableRobotsTXT = true
relativeURLs = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]
# Will give values to .Lastmod etc.
enableGitInfo = true

# ThG-Custom Changes
publishDir = "docs" # writes rendered pages to docs rather than default public. Former is expected by GitHub website deployment 

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = false
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
# pygmentsStyle = "vs"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
## not used in HUGO > 0.6
#[blackfriday]
#plainIDAnchors = true
#hrefTargetBlank = true
#angledQuotes = false
#latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-00000000-0"

# Language configuration

[languages]
[languages.en]
title = "GEN242"
description = "Spring 2021"
languageName ="English"
time_format_default = "2006-01-02"
time_format_blog = "2006-01-02"
## Weight used for sorting.
## uncomment below for more than one language support
#weight = 1
#[languages.no]
#title = "Goldydocs"
#description = "Docsy er operativsystem for skyen"
#languageName ="Norsk"
#contentDir = "content/no"
#time_format_default = "02.01.2006"
#time_format_blog = "02.01.2006"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
## markdown parse level, start with h2 headings ('##'), can be low as 1
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2
## prism.js to hightlight, comment default
#  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"


# Everything below this are Site Params
[params]
copyright = "The GEN242 Instructors"
privacy_policy = "https://www.ucr.edu/privacy.html"
favicon = "/static/img/favicon.ico"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# server location time will be used to parse timestamps in markdown headers
# See this for locations https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# if not provided, UTC will be used
serverTimeLocation = "America/Los_Angeles"

# When the "visibleDate" is specified in markdown header, how to hide the html
# one of "soft" or "hard". soft will be using javascript, hard will prevent the
# content being added at markdown rendering level
visHideMethod = "soft"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://github.com/tgirke/GEN242/"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/tgirke/GEN242/"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/tgirke/GEN242"
# Since Github change default from "master" to "main", specify here.
github_branch = "main"
# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "011737558837375720776:fsdu1nryfng"
# gcs_engine_id = "4e6b68ee2d3c1c3f1"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = true

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = true

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "v1.1dev"

# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

## The version number for the version of the docs represented in this doc set.
## Used in the "version-banner" partial to display a version number for the
## current doc set.
## uncomment below for more than one versions of website links
#version = "v1.0"

#[[params.versions]]
#  version = "v1.0"
#  githubbranch = "master"
#  url = "https://google.com"

#[[params.versions]]
#  version = "v1.1"
#  githubbranch = "master"
#  url = "https://google.com"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/tgirke/GEN242/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/tgirke/GEN242/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = true

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
#[[params.links.user]]
#	name = "User mailing list"
#	url = "https://example.org/mail"
#	icon = "fa fa-envelope"
#        desc = "Discussion and help from your fellow users"
#[[params.links.user]]
#	name ="Twitter"
#	url = "https://example.org/twitter"
#	icon = "fab fa-twitter"
#        desc = "Follow us on Twitter to get the latest news!"
#[[params.links.user]]
#	name = "Stack Overflow"
#	url = "https://example.org/stack"
#	icon = "fab fa-stack-overflow"
#        desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
#[[params.links.developer]]
#	name = "GitHub"
#	url = "https://github.com/google/docsy"
#	icon = "fab fa-github"
#        desc = "Development takes place here!"
#[[params.links.developer]]
#	name = "Slack"
#	url = "https://example.org/slack"
#	icon = "fab fa-slack"
#        desc = "Chat with other project developers"
#[[params.links.developer]]
#	name = "Developer mailing list"
#	url = "https://example.org/mail"
#	icon = "fa fa-envelope"
#        desc = "Discuss development issues around the project"


# Top-level navigation (horizontal)
##
[[menu.main]]
  name = "About"
  weight = 1
  url = "/about/"
  [[menu.main]]
    name = "Introduction"
    url = "/about/Introduction/"
    parent = "About"
    weight = 1
  [[menu.main]]
    name = "Syllabus"
    url = "/about/Syllabus/"
    parent = "About"
    weight = 2
  [[menu.main]]
    name = "Schedule"
    url = "/about/Schedule/"
    parent = "About"
    weight = 3
[[menu.main]]
  name = "Internal"
  url = "/about/internal/"
  parent = "About"
  weight = 4
  [[menu.main]]
    name = "Resources"
    url = "/about/internal/internal_resources/"
    parent = "About"
    weight = 5
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "Installation"
    url = "/about/internal/install/"
    parent = "About"
    weight = 6
    [menu.main.params]
      level = 2
##
[[menu.main]]
  name = "Slides"
  weight = 2
  url = "/slides/"
  [[menu.main]]
    name = "Course Introduction (S1)"
    url = "/slides/slides_01"
    parent = "Slides"
    weight = 101
  [[menu.main]]
    name = "Genome Basics (S2)"
    url = "/slides/slides_02"
    parent = "Slides"
    weight = 102
  [[menu.main]]
    name = "Databases and Software (S3)"
    url = "/slides/slides_03"
    parent = "Slides"
    weight = 103
  [[menu.main]]
    name = "DNA Sequencing (S4)"
    url = "/slides/slides_04"
    parent = "Slides"
    weight = 104
  [[menu.main]]
    name = "Introduction to R (S5)"
    url = "/slides/slides_05"
    parent = "Slides"
    weight = 105
  [[menu.main]]
    name = "Sequence Alignments (S6)"
    url = "/slides/slides_06"
    parent = "Slides"
    weight = 106
  [[menu.main]]
    name = "Programming in R (S7)"
    url = "/slides/slides_07"
    parent = "Slides"
    weight = 107
  [[menu.main]]
    name = "Multiple Alignments (S8)"
    url = "/slides/slides_08"
    parent = "Slides"
    weight = 108
  [[menu.main]]
    name = "Short Read Alignments (S9)"
    url = "/slides/slides_09"
    parent = "Slides"
    weight = 109
  [[menu.main]]
    name = "R on HPC (S10)"
    url = "/slides/slides_10"
    parent = "Slides"
    weight = 110
  [[menu.main]]
    name = "NGS Analysis Basics (S11)"
    url = "/slides/slides_11"
    parent = "Slides"
    weight = 111
  [[menu.main]]
    name = "Gene Expression Analysis (S12)"
    url = "/slides/slides_12"
    parent = "Slides"
    weight = 112
  [[menu.main]]
    name = "NGS Workflows (S13)"
    url = "/slides/slides_13"
    parent = "Slides"
    weight = 113
  [[menu.main]]
    name = "Slides (S14)"
    url = "/slides/slides_14/"
    parent = "Slides"
    weight = 114
  [[menu.main]]
    name = "Slides (S15)"
    url = "/slides/slides_15/"
    parent = "Slides"
    weight = 115
  [[menu.main]]
    name = "Slides (S16)"
    url = "/slides/slides_16/"
    parent = "Slides"
    weight = 116
  [[menu.main]]
    name = "Slides (S17)"
    url = "/slides/slides_17/"
    parent = "Slides"
    weight = 117
  [[menu.main]]
    name = "Slides (S18)"
    url = "/slides/slides_18/"
    parent = "Slides"
    weight = 118
  [[menu.main]]
    name = "Slides (S19)"
    url = "/slides/slides_19/"
    parent = "Slides"
    weight = 119
  [[menu.main]]
    name = "Slides (S20)"
    url = "/slides/slides_20/"
    parent = "Slides"
    weight = 120
  [[menu.main]]
    name = "Slides (S21)"
    url = "/slides/slides_21/"
    parent = "Slides"
    weight = 121
  [[menu.main]]
    name = "Slides (S22)"
    url = "/slides/slides_22/"
    parent = "Slides"
    weight = 122
##
[[menu.main]]
  name = "Tutorials"
  weight = 3
  url = "/tutorials/"
  [[menu.main]]
    name = "GitHub Introduction (T1)"
    url = "/tutorials/github/github/"
    parent = "Tutorials"
    weight = 201
  [[menu.main]]
    name = "Linux and HPCC Cluster (T2)"
    url = "/tutorials/linux/linux/"
    parent = "Tutorials"
    weight = 202
  [[menu.main]]
    name = "Introduction to R (T3)"
    url = "/tutorials/rbasics/rbasics/"
    parent = "Tutorials"
    weight = 203
  [[menu.main]]
    name = "Programming in R (T4)"
    url = "/tutorials/rprogramming/rprogramming/"
    parent = "Tutorials"
    weight = 204
  [[menu.main]]
    name = "Parallel R (T5)"
    url = "/tutorials/rparallel/rparallel/"
    parent = "Tutorials"
    weight = 205
  [[menu.main]]
    name = "NGS Analysis Basics (T6)"
    url = "/tutorials/rsequences/Rsequences/"
    parent = "Tutorials"
    weight = 206
  [[menu.main]]
    name = "Workflows (T7)"
    url = "/tutorials/systempiper/systempiper/"
    parent = "Tutorials"
    weight = 207
  [[menu.main]]
    name = "RNA-Seq Workflow (T8)"
    url = "/tutorials/sprnaseq/sprnaseq/"
    parent = "Tutorials"
    weight = 208
  [[menu.main]]
    name = "ChIP-Seq Workflow (T9)"
    url = "/tutorials/spchipseq/spchipseq/"
    parent = "Tutorials"
    weight = 209
  [[menu.main]]
    name = "scRNA-Seq Embedding Methods (T10)"
    url = "/tutorials/scrnaseq/scrnaseq/"
    parent = "Tutorials"
    weight = 210
  [[menu.main]]
    name = "R Markdown (T11)"
    url = "/tutorials/rmarkdown/rmarkdown/"
    parent = "Tutorials"
    weight = 211
  [[menu.main]]
    name = "Functional Enrichment Analysis (T12)"
    url = "/tutorials/rfea/rfea/"
    parent = "Tutorials"
    weight = 212
  [[menu.main]]
    name = "Cluster Analysis and Data Mining (T13)"
    url = "/tutorials/rclustering/rclustering/"
    parent = "Tutorials"
    weight = 213
  [[menu.main]]
    name = "Project Data (T14)"
    url = "/assignments/Projects/project_data/"
    parent = "Tutorials"
    weight = 214
  [[menu.main]]
    name = "Graphics and Visualization (T15)"
    url = "/tutorials/rgraphics/rgraphics/"
    parent = "Tutorials"
    weight = 215
  [[menu.main]]
    name = "Shiny Apps (T16)"
    url = "/tutorials/shinyapps/shinyapps/"
    parent = "Tutorials"
    weight = 216
  [[menu.main]]
    name = "Building R Packages (T17)"
    url = "/tutorials/rpackages/rpackages/"
    parent = "Tutorials"
    weight = 217
  [[menu.main]]
    name = "dplyr, tidyr and SQLite (T18)"
    url = "/tutorials/dplyr/dplyr/"
    parent = "Tutorials"
    weight = 218
  [[menu.main]]
    name = "Automate CWL Creation (T19)"
    url = "/tutorials/cmdToCwl/cmdToCwl/"
    parent = "Tutorials"
    weight = 219
##
[[menu.main]]
  name = "Assignments"
  weight = 5
  url = "/assignments/"
  [[menu.main]]
    name = "Homework"
    url = "/assignments/Homework/"
    parent = "Assignments"
    weight = 300
  [[menu.main]]
    name = "HW1: Intro & GitHub"
    url = "/assignments/Homework/HW01/HW01/"
    parent = "Assignments"
    weight = 301
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "HW2: Linux & HPC"
    url = "/assignments/Homework/HW02/HW02/"
    parent = "Assignments"
    weight = 302
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "HW3: R Basics"
    url = "/assignments/Homework/HW03/HW03/"
    parent = "Assignments"
    weight = 303
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "HW4: Alignments"
    url = "/assignments/Homework/HW04/HW04/"
    parent = "Assignments"
    weight = 304
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "HW5: R Programming"
    url = "/assignments/Homework/HW05/HW05"
    parent = "Assignments"
    weight = 305
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "HW6: NGS Analysis Basics"
    url = "/assignments/Homework/HW06/HW06"
    parent = "Assignments"
    weight = 306
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "HW7: RNA-Seq Analysis"
    url = "/assignments/Homework/HW07/HW07"
    parent = "Assignments"
    weight = 307
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "HW8"
    url = "/assignments/Homework/HW08/HW08"
    parent = "Assignments"
    weight = 308
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "Projects"
    url = "/assignments/Projects/"
    parent = "Assignments"
    weight = 400
  [[menu.main]]
    name = "Overview of Projects"
    url = "/assignments/Projects/project_overview/"
    parent = "Assignments"
    weight = 401
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "RNA-Seq Aligners"
    url = "/assignments/Projects/01_rnaseq_aligners/"
    parent = "Assignments"
    weight = 402
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "DEG Methods"
    url = "/assignments/Projects/02_rnaseq_deg/"
    parent = "Assignments"
    weight = 403
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "Cluster Analysis"
    url = "/assignments/Projects/03_cluster_analysis/"
    parent = "Assignments"
    weight = 404
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "scRNA-Seq Embedding"
    url = "/assignments/Projects/04_scrnaseq_embedding/"
    parent = "Assignments"
    weight = 405
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "ChIP-Seq Peak Callers"
    url = "/assignments/Projects/05_chipseq_peakcaller/"
    parent = "Assignments"
    weight = 406
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "Functional Enrichment"
    url = "/assignments/Projects/06_functional_enrichment/"
    parent = "Assignments"
    weight = 407
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "Motif Enrichment"
    url = "/assignments/Projects/07_motif_enrichment/"
    parent = "Assignments"
    weight = 408
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "Genome Graphics"
    url = "/assignments/Projects/08_genome_graphics/"
    parent = "Assignments"
    weight = 409
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "Project Data"
    url = "/assignments/Projects/project_data/"
    parent = "Assignments"
    weight = 409
    [menu.main.params]
      level = 2
  [[menu.main]]
    name = "Presentations"
    url = "/assignments/Presentations/"
    parent = "Assignments"
    weight = 500
  [[menu.main]]
    name = "Paper Presentations"
    url = "/assignments/Presentations/paper_presentations/"
    parent = "Assignments"
    weight = 501
    [menu.main.params]
      level = 2
## 
[[menu.main]]
  name = "Links"
  url = "/external_resources/"
  weight = 6
  [[menu.main]]
    name = "Piazza"
    url = "https://piazza.com/ucr/spring2022/gen242/home"
    parent = "Links"
    weight = 1
  [[menu.main]]
    name = "GitHub Classroom"
    url = "https://classroom.github.com/classrooms/"
    parent = "Links"
    weight = 2
  [[menu.main]]
    name = "GitHub Repo"
    url = "https://github.com/tgirke/GEN242"
    parent = "Links"
    weight = 3
  [[menu.main]]
    name = "Bioconductor"
    url = "https://bioconductor.org/"
    parent = "Links"
    weight = 4
  [[menu.main]]
    name = "Hugo, Docsy & R"
    url = "https://www.dcassol.com/docsy_Rmarkdown/rmarkdown/install/"
    parent = "Links"
    weight = 5

